{
  "cveMetadata": {
    "state": "PUBLISHED",
    "cveId": "CVE-2022-45198",
    "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
    "assignerShortName": "mitre",
    "dateUpdated": "2024-08-03T14:09:56.639Z",
    "dateReserved": "2022-11-14T00:00:00",
    "datePublished": "2022-11-14T00:00:00"
  },
  "containers": {
    "adp": [
      {
        "providerMetadata": {
          "orgId": "af854a3a-2127-422b-91ae-364da2661108",
          "shortName": "CVE",
          "dateUpdated": "2024-08-03T14:09:56.639Z"
        },
        "title": "CVE Program Container",
        "references": [
          {
            "url": "https://github.com/python-pillow/Pillow/commit/11918eac0628ec8ac0812670d9838361ead2d6a4",
            "tags": [
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/python-pillow/Pillow/pull/6402",
            "tags": [
              "x_transferred"
            ]
          },
          {
            "url": "https://bugs.gentoo.org/855683",
            "tags": [
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/python-pillow/Pillow/releases/tag/9.2.0",
            "tags": [
              "x_transferred"
            ]
          },
          {
            "url": "https://cwe.mitre.org/data/definitions/409.html",
            "tags": [
              "x_transferred"
            ]
          },
          {
            "name": "GLSA-202211-10",
            "tags": [
              "vendor-advisory",
              "x_transferred"
            ],
            "url": "https://security.gentoo.org/glsa/202211-10"
          }
        ]
      }
    ]
  },
  "search": "解析验收测试文案"
}