{
  "cveMetadata": {
    "state": "PUBLISHED",
    "cveId": "CVE-2022-48564",
    "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
    "assignerShortName": "mitre",
    "dateUpdated": "2024-08-03T15:17:54.746Z",
    "dateReserved": "2023-07-23T00:00:00",
    "datePublished": "2023-08-22T00:00:00"
  },
  "containers": {
    "adp": [
      {
        "providerMetadata": {
          "orgId": "af854a3a-2127-422b-91ae-364da2661108",
          "shortName": "CVE",
          "dateUpdated": "2024-08-03T15:17:54.746Z"
        },
        "title": "CVE Program Container",
        "references": [
          {
            "url": "https://bugs.python.org/issue42103",
            "tags": [
              "x_transferred"
            ]
          },
          {
            "url": "https://security.netapp.com/advisory/ntap-20230929-0009/",
            "tags": [
              "x_transferred"
            ]
          },
          {
            "name": "[debian-lts-announce] 20231011 [SECURITY] [DLA 3614-1] python3.7 security update",
            "tags": [
              "mailing-list",
              "x_transferred"
            ],
            "url": "https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html"
          }
        ]
      }
    ]
  },
  "search": "解析验收测试文案"
}